### ISSUE TITLE
函数计算执行报错

### ISSUE THREAD

**Issue by AngelaZhao** [baidu/openedge#145]
**Describe the bug**
函数计算执行报错，具体日志如下
![image](https://user-images.githubusercontent.com/6222260/54810236-917f9480-4cc0-11e9-8ac7-3b12aed6221a.png)

![image](https://user-images.githubusercontent.com/6222260/54810260-a0664700-4cc0-11e9-850a-11acbf6d3ecd.png)

**To Reproduce**
函数计算部分的配置如下（缩进有些问题）：
application.yml文件
services:
  \- name: function-manager
    image: cp01-caas-registry.epc.baidu.com:8000/iottest/openedge-function-manager:latest
    replica: 1
    mounts:
      \- name: function-manager-conf
        path: etc/openedge
        readonly: true
      \- name: function-manager-log
        path: var/log/openedge
  \- name: function-sayhi
    image: cp01-caas-registry.epc.baidu.com:8000/iottest/openedge-function-python27:latest
    replica: 0
    mounts:
      \- name: function-sayhi-conf
        path: etc/openedge
        readonly: true
      \- name: function-sayhi-code
        path: var/db/openedge/function-sayhi
        readonly: true
volumes:
\# function
 \- name: function-manager-conf
    path: var/db/openedge/function-manager-conf
  \- name: function-manager-log
    path: var/db/log/openedge/function-manager-log
  \- name: function-sayhi-conf
    path: var/db/openedge/function-sayhi-conf
  \- name: function-sayhi-code
    path: var/db/openedge/function-sayhi-code

var/db/openedge/function-manager-conf/service.yml文件
hub:
  address: tcp://openedge_hub:8963
  username: test
  password: test
rules:
  \- clientid: rule-e1iluuac15
    subscribe:
      topic: python/function/test
      qos: 1
    function:
      name: sayhi
    publish:
      topic: python/function/result

var/db/openedge/function-sayhi-conf/service.yml文件
functions:
  \- name: 'sayhi'
    handler: 'sayhi.handler'
    codedir: 'var/db/openedge/function-sayhi'

**Comment by ludanfeng** [comment]
fixed #146
