### ISSUE TITLE
进程模式openedge无法启动

### ISSUE THREAD

**Issue by AngelaZhao** [baidu/openedge#157]
**Describe the bug**
进程模式openedge无法启动
日志截图如下
![image](https://user-images.githubusercontent.com/6222260/54999011-5d7ed900-500a-11e9-8dbc-4b6730fffab8.png)

var/run/openedge/services目录如下
![image](https://user-images.githubusercontent.com/6222260/54999045-6a9bc800-500a-11e9-81af-57896c12ffe9.png)

**To Reproduce**
application.yml配置如下，其中openedge-hub的bin文件在var/db/openedge/openedge-hub目录下
![image](https://user-images.githubusercontent.com/6222260/54999202-b2baea80-500a-11e9-90a2-f56d1ca3a24d.png)

localhub-conf/service.yml配置如下
![image](https://user-images.githubusercontent.com/6222260/54999561-763bbe80-500b-11e9-85a9-c08d39616336.png)

**Comment by ludanfeng** [comment]
目前进程模式需要用户自己准备模块程序
