### ISSUE TITLE
openedge  -w example/docker/ 报错

### ISSUE THREAD

**Issue by Azuriteage** [baidu/openedge#160]
root@raspberrypi:/usr/local/gowork/src/github.com/baidu/openedge# openedge -w example/docker/
Error: unknown shorthand flag: 'w' in -w
Usage:
  openedge [command]

Available Commands:
  help        Help about any command
  start       start openedge on background
  stop        stop openedge and all services
  version     Show the OpenEdge version information

Flags:
  -h, --help   help for openedge

Use "openedge [command] --help" for more information about a command.

2019/03/29 13:54:41 unknown shorthand flag: 'w' in -w

参照从源码编译文档入门，docker 镜像生成成功，make install正常,运行程序就是上面这段，请问是我那一部分没有操作对吗？

**Comment by ludanfeng** [comment]
你现在使用的是master分支的代码，已经退出命令行工具，请参考命令行的提示操作。
文档还是旧版的，我们正在抓紧推出新版文档。
多谢关注

**Comment by kuailehaibin** [comment]
@Azuriteage 新版本文档已经推出，详情查看 [https://openedge.tech](https://openedge.tech)
