### ISSUE TITLE
remote配置replica=0，instance无法启动；replica>1连接不停断连重连

### ISSUE THREAD

**Issue by AngelaZhao** [baidu/openedge#161]
**Describe the bug**
remote配置replica=0，instance无法启动
主程序的日志中只看到了一条相关日志
![image](https://user-images.githubusercontent.com/6222260/55221801-5394ea00-5245-11e9-9a3d-15530688d6c6.png)

remote配置replica=2，hub和remote的连接都在不停的断连再重连，看上去像是连接已经建立后，又再次用相同的client id去把之前的连接踢掉
![image](https://user-images.githubusercontent.com/6222260/55230197-07a07000-525a-11e9-8938-38fb557226bf.png)
wireshark抓包，每次connect返回的connack都是连接成功
![image](https://user-images.githubusercontent.com/6222260/55230287-50582900-525a-11e9-9eab-a53bc37a321c.png)

**To Reproduce**
remote配置
![image](https://user-images.githubusercontent.com/6222260/55221836-68717d80-5245-11e9-8e1b-093d1f08eb60.png)

**Comment by ludanfeng** [comment]
符合预期，replica=0表示不启动实例，replica>1表示启动多个实例，不是所有模块都支持启动多个实例，因为配置是共用的，会出现冲突。所有官方模块都只能启动一个副本，比如监听端口冲突、clientid冲突等。适合多实例启动的模块是那种可以并发执行任务的，比如启动10各worker实例同时向某个服务获取事务并行处理。
