### ISSUE TITLE
make images报错

### ISSUE THREAD

**Issue by jinyucn** [baidu/openedge#167]
Pulling repository docker.io/library/golang
Tag alpine as builder not found in repository docker.io/library/golang
make[1]: *** [openedge-hub-image] 错误 1
make[1]:正在离开目录 `/home/chenjinyu/openedge/go/src/github.com/baidu/openedge/openedge-hub'
make: *** [openedge-hub-image] 错误 2
 在make images报这个错，请问怎么解决呢？

**Comment by ludanfeng** [comment]
可能docker版本太低了，不支持多步构建
OpenEdge 0.1.2 y已经推出，新版命令为 make image
