### ISSUE TITLE
针对教程中如何引用第三方包

### ISSUE THREAD

**Issue by michloas** [baidu/openedge#180]
我参考了  https://github.com/baidu/openedge/issues/95 提到的方式，但是发现回答中提到的方式和官网中说的是一样的https://openedge.tech/zh/docs/customize/How-to-write-a-python-script-for-python-runtime

我是通过在百度云CFC函数中新建的函数，使用的是官方文档提供的函数
![image](https://user-images.githubusercontent.com/29136108/55448253-a54cc400-55f9-11e9-8f6e-3c26905c3a43.png)

然后在本地计算函数模块配置这个函数，并且下发配置到本地
![image](https://user-images.githubusercontent.com/29136108/55448317-dfb66100-55f9-11e9-8e7f-22a0f25d3f4e.png)

下发到本地之后函数目录文件的情况
![image](https://user-images.githubusercontent.com/29136108/55448376-17250d80-55fa-11e9-93ad-83d53e7b8697.png)

按照 https://github.com/baidu/openedge/issues/95 提供的方式，执行完成之后是这样的：
![image](https://user-images.githubusercontent.com/29136108/55448854-fcec2f00-55fb-11e9-9617-6c8903dc5880.png)

我发现这个和文档中的不一致，所以我把这些下载的删除掉了，重新拷贝了下载在`/usr/lib/python2.7/dist-packages/` 路径下的包，如下图
![image](https://user-images.githubusercontent.com/29136108/55449677-0fb43300-55ff-11e9-9653-f758b8a28071.png)

使用MQTTBox发送消息之后发现报错的信息和  https://github.com/baidu/openedge/issues/95 是一致的

**Comment by kuailehaibin** [comment]
@michloas 不用修改，直接采用 [#95](https://github.com/baidu/openedge/issues/95)的方式进行测试，如有问题，请描述清楚，谢谢！

**Comment by michloas** [comment]
> @michloas 不用修改，直接采用 [#95](https://github.com/baidu/openedge/issues/95)的方式进行测试，如有问题，请描述清楚，谢谢！

我发现问题了，实际上这个示例函数已经拿到了返回值，只不过报错了，package的引入应该是没有问题的
`time="2019-04-03T09:30:38Z" level=error msg="failed to talk with function instance" error="rpc error: code = Unknown desc = Exception calling application: {'Content-Length': '6204', 'X-Powered-By': 'Express', 'Strict-Transport-Security': 'max-age=63072000; includeSubdomains; preload', 'Server': 'nginx/1.15.9', 'Connection': 'keep-alive', 'ETag': 'W/\"183c-skx9JbhDJWpQL5uJ4m8+Smp3qzc\"', 'Date': 'Wed, 03 Apr 2019 09:30:38 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'text/html; charset=utf-8'} is not JSON serializable" function=calculation-test-request-1 module=local_calculation
`

**Comment by kuailehaibin** [comment]
@michloas 看提示信息是说获取的内容没有进行 JSON 序列化导致，方便的话，贴一下完整的执行脚本内容。

**Comment by michloas** [comment]
@kuailehaibin 我使用的脚本就是官方网站中 https://openedge.tech/zh/docs/customize/How-to-write-a-python-script-for-python-runtime 在如何引用第三方包中提供的脚本：
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import requests

def handler(event, context):
  """
  data: {"action": "A"}
  """
  if 'action' in event:
    if event['action'] == 'A':
      r = requests.get('https://openedge.tech')
      if str(r.status_code) == '200':
        event['info'] = r.headers
      else:
        event['info'] = 'exception found'
    else:
      event['info'] = 'action error'
  else:
    event['error'] = 'action not found'

  return event
```
当我输入的数据是 **{"action": "A"}** 时，就会出现贴出来的报错信息
```
time="2019-04-03T09:30:38Z" level=error msg="failed to talk with function instance" error="rpc error: code = Unknown desc = Exception calling application: {'Content-Length': '6204', 'X-Powered-By': 'Express', 'Strict-Transport-Security': 'max-age=63072000; includeSubdomains; preload', 'Server': 'nginx/1.15.9', 'Connection': 'keep-alive', 'ETag': 'W/\"183c-skx9JbhDJWpQL5uJ4m8+Smp3qzc\"', 'Date': 'Wed, 03 Apr 2019 09:30:38 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'text/html; charset=utf-8'} is not JSON serializable" function=calculation-test-request-1 module=local_calculation
```

**Comment by kuailehaibin** [comment]
@michloas 是用最新 0.1.2 的版本测试的吗？我们官网的文档已经随着 OpenEdge 新发布的版本调整、更新，建议参考最新的文档来测试，如果还有问题，请及时反馈，谢谢！

**Comment by michloas** [comment]
@kuailehaibin 这是0.1.1版本遇到的问题，我们会在 0.1.2 版本上继续尝试的。

**Comment by kuailehaibin** [comment]
@michloas 好的，辛苦
