### ISSUE TITLE
Mac OS 下，提示./bin/openedge: cannot execute binary file

### ISSUE THREAD

**Issue by SullivanJia** [baidu/openedge#217]
![image](https://user-images.githubusercontent.com/26838155/56628506-a9aa5100-667c-11e9-9d38-3e49dced5fe8.png)
已经修改权限，但是还是无法再mac电脑上使用openedge start

**Comment by wlwgcdxc** [comment]
执行`echo $GOOS `，看一下是不是darwin

**Comment by ludanfeng** [comment]
@SullivanJia OpenEdge是源码编译的还是BIE云端下载的？

**Comment by SullivanJia** [comment]
> @SullivanJia OpenEdge是源码编译的还是BIE云端下载的？
BIE云下载的

**Comment by ludanfeng** [comment]
@SullivanJia 这个问题一帮是平台不一致造成，CPU和系统都要对上。请问你下载的OpenEdge是MacOS版本吗？

**Comment by ludanfeng** [comment]
为了提供沟通效率，欢迎进微信群：https://openedge.bj.bcebos.com/Wechat/Wechat-OpenEdge.png

**Comment by SullivanJia** [comment]
@ludanfeng 
![{631D6946-7EDA-3BDA-50E9-ABBABFEE9A40}](https://user-images.githubusercontent.com/26838155/57276672-daef3c00-70d4-11e9-80e5-cd63d0b3eb7c.jpg)
这个是darwin版本
![{F35E4E97-E0AA-9111-81DA-716D67193325}](https://user-images.githubusercontent.com/26838155/57276695-efcbcf80-70d4-11e9-8687-c53fc3222298.jpg)
这个是我的下载的Openedge版本。

**Comment by ludanfeng** [comment]
的确很奇怪，chmod +x 了吗？

**Comment by SullivanJia** [comment]
试过了还有 chmod -R 777 也不行

**Comment by ludanfeng** [comment]
我们先记录一下这个问题
你可以自己试试源码编译吗？

**Comment by sherlockblaze** [comment]
@SullivanJia 您好、辛苦进入上面链接提供的微信群，方便我们沟通解决问题，谢谢
