### ISSUE TITLE
函数计算消息处理获取qos 错误

### ISSUE THREAD

**Issue by gigi5700** [baidu/openedge#223]
复现步骤：
1.  openedge 包含以下函数路由（python2.7）
![image](https://user-images.githubusercontent.com/36956936/56951705-1df85f00-6b6b-11e9-9fb0-72d15058aa7d.png)
2. 往srcTopic以qos=1发送消息后，dest中收到的消息qos = 0
![image](https://user-images.githubusercontent.com/36956936/56951943-a414a580-6b6b-11e9-94e7-e14f95f7935f.png)

**Comment by ludanfeng** [comment]
@gigi5700 函数计算订阅和发布的QOS默认是0，配置参考：https://github.com/baidu/openedge/blob/master/doc/zh-cn/tutorials/Config-interpretation.md#openedge-function-manager-%E9%85%8D%E7%BD%AE
