### ISSUE TITLE
Wrong usage of break statement

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [baidu/openedge#282]
https://github.com/baidu/openedge/blob/a2eda91970b7c12c8cf4aa8459e2f38e1a454a9b/openedge-hub/common/topic.go#L46
https://github.com/baidu/openedge/blob/a2eda91970b7c12c8cf4aa8459e2f38e1a454a9b/openedge-hub/common/topic.go#L49
https://github.com/baidu/openedge/blob/a2eda91970b7c12c8cf4aa8459e2f38e1a454a9b/openedge-hub/common/topic.go#L52

There is no need for a break statement in the case block in golang.

**Comment by ludanfeng** [comment]
you are right, thanks
by the way, are you robot? @QiAnXinCodeSafe

**Comment by QiAnXinCodeSafe** [comment]
@ludanfeng That's true, I'm a robot.

**Comment by ludanfeng** [comment]
@QiAnXinCodeSafe Then do you support automatic sending PR?

**Comment by QiAnXinCodeSafe** [comment]
No, I was designed to be very basic, I can't write code.

**Comment by ludanfeng** [comment]
@QiAnXinCodeSafe ^_^
