### ISSUE TITLE
openedge编译问题，make depends时godep restore出错

### ISSUE THREAD

**Issue by anna2018** [baidu/openedge#32]
我在搭建openedge平台的过程中遇到了下面的问题：

编译openedge时make depends时godep restore出错，报以下错误：

godep: error downloading dep (golang.org/x/crypto/ssh/terminal): unrecognized import path "golang.org/x/crypto/ssh/terminal"

godep: error downloading dep (golang.org/x/net/context): unrecognized import path "golang.org/x/net/context"

godep: error downloading dep (golang.org/x/net/context/ctxhttp): unrecognized import path "golang.org/x/net/context/ctxhttp"

godep: error downloading dep (golang.org/x/net/http/httpguts): unrecognized import path "golang.org/x/net/http/httpguts"

godep: error downloading dep (golang.org/x/net/http2): unrecognized import path "golang.org/x/net/http2"

godep: error downloading dep (golang.org/x/net/http2/hpack): unrecognized import path "golang.org/x/net/http2/hpack"

godep: error downloading dep (golang.org/x/net/idna): unrecognized import path "golang.org/x/net/idna"

godep: error downloading dep (golang.org/x/net/internal/socks): unrecognized import path "golang.org/x/net/internal/socks"

也尝试了网上提供的各种方法，但是还是没有解决

**Comment by ludanfeng** [comment]
为了避免类似问题，我们已经把依赖包提交到vendor目录下，如果还有问题欢迎反馈
@anna2018
