### ISSUE TITLE
make编译出错

### ISSUE THREAD

**Issue by anna2018** [baidu/openedge#35]
make编译的时候报下面的错误

GO openedge 
# github.com/baidu/openedge/module
module/flag.go:60:30: flag.CommandLine.Output undefined (type *flag.FlagSet has no field or method Output, but does have flag.output)

**Comment by kuailehaibin** [comment]
这个问题比较奇怪，建议您选择如下两种方式：
1）拉取最新代码，重新编译测试看看；
2）提供您的代码编译环境，如golang版本，拉取本代码的git版本号等。

谢谢！

**Comment by ludanfeng** [comment]
@anna2018 请问问题解决了吗？
现在项目的编译脚本基本都切换到makefile了，依赖也采用了vendor管理，应该能彻底解决编译问题了，多谢您的反馈。

**Comment by anna2018** [comment]
这个问题已经解决了，现在卡在openedge -w example/docker这一步，出现下面这个问题，请帮忙看一下
INFO[2018-12-25T18:59:34-08:00] network (8e283b334ade:openedge) exists        mode=docker openedge=master
WARN[2018-12-25T18:59:39-08:00] failed to prepare entries                     error="Error response from daemon: pull access denied for openedge-hub, repository does not exist or may require 'docker login';Error response from daemon: pull access denied for openedge-function, repository does not exist or may require 'docker login';" mode=docker openedge=master
WARN[2018-12-25T18:59:39-08:00] failed to create container                    error="Error: No such image: openedge-hub:build" module=localhub openedge=master
WARN[2018-12-25T18:59:39-08:00] failed to create container again              error="Error: No such image: openedge-hub:build" module=localhub openedge=master
ERRO[2018-12-25T18:59:39-08:00] failed to start resident module (localhub)    error="Error: No such image: openedge-hub:build" mode=docker openedge=master
failed to start master: Error: No such image: openedge-hub:build
INFO[2018-12-25T18:59:39-08:00] resident module (localhub) stopped            mode=docker openedge=master
INFO[2018-12-25T18:59:39-08:00] all resident modules stopped                  mode=docker openedge=master
INFO[2018-12-25T18:59:39-08:00] all temporary modules stopped                 mode=docker openedge=master

**Comment by kuailehaibin** [comment]
@anna2018 您好！这个问题是这样的：
现在最新master主分支的代码，相比0.1.0版本，代码组织目录结构、镜像打包名称等有些变化，新版本Docker容器模式的官方镜像并未发布，故以容器模式启动时候会出现这类问题。预计这两天Openedge的新版本即会发布，同步更新官方镜像。还请您耐心等待，或是先使用Native进程模式，由此给您带来的不便，敬请谅解，再次感谢您的反馈！

**Comment by ludanfeng** [comment]
@anna2018  为了解决本地镜像测试问题，我们提供了`make images`命令，可以在本地产出模块镜像，tag的命名方式是：<module_name>:build。所以你要先本地执行一下这个命令来生成镜像。我们正在更新文档，会输出此类说明。如有问题继续反馈。为了提高沟通效率欢迎加入我们的微信开发交流群：[OpenEdge开发交流群](https://openedge.bj.bcebos.com/Wechat/Wechat-OpenEdge.png)

**Comment by KArtorias** [comment]
请问下  module/flag.go:60:30: flag.CommandLine.Output undefined (type *flag.FlagSet has no field or method Output, but does have flag.output) 这个问题怎么解决的啊，安装gopls时候遇上了
