### ISSUE TITLE
树莓派3B openedge -w example/docker 错误

### ISSUE THREAD

**Issue by caokebo** [baidu/openedge#56]
root@raspberrypi:/usr/local/go/src/github.com/baidu/openedge# openedge -w example/docker
DEBU[2018-12-28T18:09:13+08:00] work dir: /usr/local/go/src/github.com/baidu/openedge/example/docker  openedge=master
INFO[2018-12-28T18:09:13+08:00] network (835d9d5851b5:openedge) exists        mode=docker openedge=master
WARN[2018-12-28T18:09:17+08:00] failed to prepare entries                     error="Error response from daemon: pull access denied for openedge-hub, repository does not exist or may require 'docker login';Error response from daemon: pull access denied for openedge-function, repository does not exist or may require 'docker login';" mode=docker openedge=master
INFO[2018-12-28T18:09:20+08:00] container started                             cid=f6ddd03911f2 module=localhub openedge=master
INFO[2018-12-28T18:09:20+08:00] resident module (localhub) started            mode=docker openedge=master
WARN[2018-12-28T18:09:20+08:00] failed to create container                    error="Error response from daemon: NanoCPUs can not be set, as your kernel does not support CPU cfs period/quota or the cgroup is not mounted" module=localfunc openedge=master
WARN[2018-12-28T18:09:20+08:00] failed to create container again              error="Error response from daemon: NanoCPUs can not be set, as your kernel does not support CPU cfs period/quota or the cgroup is not mounted" module=localfunc openedge=master
ERRO[2018-12-28T18:09:20+08:00] failed to start resident module (localfunc)   error="Error response from daemon: NanoCPUs can not be set, as your kernel does not support CPU cfs period/quota or the cgroup is not mounted" mode=docker openedge=master
failed to start master: Error response from daemon: NanoCPUs can not be set, as your kernel does not support CPU cfs period/quota or the cgroup is not mounted
INFO[2018-12-28T18:09:20+08:00] resident module (localfunc) stopped           mode=docker openedge=master
INFO[2018-12-28T18:09:21+08:00] container exited: {<nil> 2}                   cid=f6ddd03911f2 module=localhub openedge=master
INFO[2018-12-28T18:09:21+08:00] container stopped                             cid=f6ddd03911f2 module=localhub openedge=master
INFO[2018-12-28T18:09:21+08:00] container removed                             cid=f6ddd03911f2 module=localhub openedge=master
INFO[2018-12-28T18:09:21+08:00] resident module (localhub) stopped            mode=docker openedge=master
INFO[2018-12-28T18:09:21+08:00] all resident modules stopped                  mode=docker openedge=master
INFO[2018-12-28T18:09:21+08:00] all temporary modules stopped                 mode=docker openedge=master

native模式运行没问题

**Comment by ludanfeng** [comment]
恩，看日志是你的环境下的docker不支持配置NanoCPUs来限制CPU资源，我们会尽快安排修复，谢谢反馈。另外可否提供你的树莓派的型号、系统和CPU类型等环境消息，以及docker的版本？

**Comment by ludanfeng** [comment]
@caokebo 多谢反馈。如果你是源码安装，可以先把[https://github.com/baidu/openedge/blob/master/engine/docker_engine.go](https://github.com/baidu/openedge/blob/master/engine/docker_engine.go)的第88行注释掉试试。我们会安排节后修复这个问题。

**Comment by sherlockblaze** [comment]
@caokebo 

多谢反馈，以下是详细原因和相关的解决方案。

## 原因

Cfs is not compiled for the Raspbian kernel.

树莓派上系统内核在编译时未设置 CON-FIG_CFS_BANDWIDTH，致使RespBian Kernel不支持CPU CFS Quata以及CPU CFS Period

## 解决方案

使用以下命令查看 docker 层面相关信息：

```shell
docker info
```

观察最后是否有如下 Warning:

```
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

其中上面三个为内存资源限制相关，后两个为CPU资源限制相关。

如您需要使用内存资源限制功能，请编辑 ```/boot/cmdline.txt``` 文件，在其后加入 ***cgroup_enable=memory swapaccount=1*** 两个参数，完成后重启系统，再使用  ```docker info``` 命令查看相关信息。

如上述 Warning 变更为:

```
WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

此时您可使用 OpenEdge 内存资源限制功能，但因内核原因限制，cpu 资源限制功能以及 memory swap 资源限制功能不被支持，请您知悉。

同时，你需要修改OpenEdge配置文件中资源限制相关的设置，比如移除模块或者函数实例的CPU资源限制或者memory swap资源限制。可在[配置解读](https://openedge.tech/docs/tutorials/local/Config-interpretation)文档中搜索CPU或memory查看相关信息。

## 后续安排

后续开发中，我们会让OpenEdge拥有以下能力：
1. 识别不支持，并输出相关warning日志，保持openedge继续运行。
2. 提供更丰富的资源限制功能

**Comment by xwdreamer** [comment]
> @caokebo
> 
> 多谢反馈，以下是详细原因和相关的解决方案。
> 
> ## 原因
> Cfs is not compiled for the Raspbian kernel.
> 
> 树莓派上系统内核在编译时未设置 CON-FIG_CFS_BANDWIDTH，致使RespBian Kernel不支持CPU CFS Quata以及CPU CFS Period
> 
> ## 解决方案
> 使用以下命令查看 docker 层面相关信息：
> 
> ```shell
> docker info
> ```
> 
> 观察最后是否有如下 Warning:
> 
> ```
> WARNING: No memory limit support
> WARNING: No swap limit support
> WARNING: No kernel memory limit support
> WARNING: No oom kill disable support
> WARNING: No cpu cfs quota support
> WARNING: No cpu cfs period support
> ```
> 其中上面三个为内存资源限制相关，后两个为CPU资源限制相关。
> 
> 如您需要使用内存资源限制功能，请编辑 `/boot/cmdline.txt` 文件，在其后加入 _**cgroup_enable=memory swapaccount=1**_ 两个参数，完成后重启系统，再使用 `docker info` 命令查看相关信息。
> 
> 如上述 Warning 变更为:
> 
> ```
> WARNING: No swap limit support
> WARNING: No cpu cfs quota support
> WARNING: No cpu cfs period support
> ```
> 此时您可使用 OpenEdge 内存资源限制功能，但因内核原因限制，cpu 资源限制功能以及 memory swap 资源限制功能不被支持，请您知悉。
> 
> 同时，你需要修改OpenEdge配置文件中资源限制相关的设置，比如移除模块或者函数实例的CPU资源限制或者memory swap资源限制。可在[配置解读](https://openedge.tech/docs/tutorials/local/Config-interpretation)文档中搜索CPU或memory查看相关信息。
> 
> ## 后续安排
> 后续开发中，我们会让OpenEdge拥有以下能力：
> 
> 1. 识别不支持，并输出相关warning日志，保持openedge继续运行。
> 2. 提供更丰富的资源限制功能

这个后续安排大概什么时候可以上线。我用的也是树莓派3B+，碰到同样的问题。

**Comment by xwdreamer** [comment]
按照@sherlockblaze 说的，我去查看了配置解读，发现配置openedge.yml如下图所示，没有任何swap和cpu相关的内容，这样如何去掉cpu和memory相关的配置？

![image](https://user-images.githubusercontent.com/1173919/51174032-c999de00-18f1-11e9-990e-1495e0a9cc0a.png)

**Comment by xwdreamer** [comment]
localfunc当中存在同样的问题，需要注意。
![image](https://user-images.githubusercontent.com/1173919/51290150-f824cf80-1a3d-11e9-967d-ae9a5b2af24c.png)
