### ISSUE TITLE
openedge_function can only been triggered by local mqtt client

### ISSUE THREAD

**Issue by tongtongxiaopeng1979** [baidu/openedge#59]
Currently according to user guide, MQTT client can access openedge_function via openedge_hub.
The data path is: MQTT client -> openedge_hub -> openedge_function -> openedge_hub->MQTT Client

if the MQTT client wants to access openedge_funcation via baidu_iothub, it will not work
The expected data path is: MQTT client -> iothub -> openedge_remote_mqtt -> openedge_hub->openedge_function.

**Comment by tongtongxiaopeng1979** [comment]
> @tongtongxiaopeng1979
> More about remote module user-guide：https://openedge.tech/docs/tutorials/local/Message-synchronize-with-iothub-whith-remote-module
> 
> If you want to access openedge-function via baidu-iothub, the data path is : MQTT client(for baidu-iothub) -> baidu-iothub -> openedge-mqtt-remote -> openedge-hub -> openedge-function -> openedge-hub -> MQTT client(for openedge).

thanks for your reply .  there is one question
when you create a openedge_function module for the local hub, you have to fill in the "Privilege name". The priviledge name actually is the permission to local hub. so it means mqtt_remote not have permission to access openedge-function. is it correct?

**Comment by kuailehaibin** [comment]
@tongtongxiaopeng1979 
Yeah, actually, all module messages need to go through the hub module, and messages processing depends on `rule config`.

**Comment by ludanfeng** [comment]
@tongtongxiaopeng1979 先问个问题：如果消息（数据）已经上云了，为何不在云端接着处理消息？比如使用CFC。OpenEdge的使用场景是在边缘采集和处理消息，然后上云，而不是反过来。
Ask a question first: If the message (data) is already in the cloud, why not continue to process the message in the cloud? For example, use [CFC](https://cloud.baidu.com/product/cfc.html). The use of OpenEdge is to collect and process messages at the edge and then sync to the cloud instead of the other way around.

**Comment by tongtongxiaopeng1979** [comment]
@ludanfeng 
You are right, it is typical use case for the data path you mentioned .  But there is a special use case that need to use FAAS in the openEdge to implement communication with other application or platform in the same host.

这个用例比较特殊，如果openEdge是架构在用户其他平台上面，用户可能会利用openedge FC功能和用户其他平台进行交互。该交互可以由远程一个client触发。

**Comment by ludanfeng** [comment]
@tongtongxiaopeng1979 你看看下面几种方式哪个更适合你们：
1. [TODO]openedge的函数计算直接暴露grpc接口，提供给远程grpc client调用
2. [TODO]openedge支持远程mqtt server直接作为本地hub使用，即把mqtt remote当做本地hub
3. 如同 @kuailehaibin 描述的方案将远程消息先使用mqtt client发送到openedge的本地hub，再通过路由规则触发函数计算

**Comment by tongtongxiaopeng1979** [comment]
@ludanfeng 先按照mengtao的方法吧，我们公司不是做行业应用和业务的，只不过我手边有个项目有个特殊需求而已。

至于 1 和 2 做不做,还是你们和行业客户来决定吧。

好的，已经加入沟通交流微信群了。 这个问题我先关闭，谢谢你们指导  : )
