### ISSUE TITLE
use "make images" or "make image"

### ISSUE THREAD

**Issue by xwdreamer** [baidu/openedge#80]
when I use make images, it reports : make: *** No rule to make target 'images'.  Stop.
![image](https://user-images.githubusercontent.com/1173919/51244986-742d0200-19c1-11e9-8a7b-9a35930ac401.png)

when I use make image, this cmd successfully.
![image](https://user-images.githubusercontent.com/1173919/51245027-8a3ac280-19c1-11e9-96ab-f281e9af84bb.png)

which cmd is right?

**Comment by ludanfeng** [comment]
use 'image' on master branch, and 'images' on 0.1.1 tag.
we are refactoring code on 'master' now, it is a big break change: https://github.com/baidu/openedge/pull/78
So, please use the code for 0.1.1 tag for build and test, which can connect with BIE on cloud.

**Comment by xwdreamer** [comment]
ok, thanks.

**Comment by ludanfeng** [comment]
@xwdreamer 你好，请问加[OpenEdge微信交流群](https://openedge.bj.bcebos.com/Wechat/Wechat-OpenEdge.png)了吗？我们可以及时交流
