### ISSUE TITLE
When start bin/openedge , Get "failed to create master: listen unix var/run/openedge.sock: bind: address already in use" error！

### ISSUE THREAD

**Issue by hwangyungping** [baidu/openedge#81]
[root@localhost OpenEdge]# bin/openedge
DEBU[2019-01-16T05:48:30-05:00] work dir: /home/OpenEdge                      openedge=master
INFO[2019-01-16T05:48:30-05:00] network (23f72b44b7cd:openedge) exists        mode=docker openedge=master
INFO[2019-01-16T05:48:30-05:00] all resident modules stopped                  mode=docker openedge=master
INFO[2019-01-16T05:48:30-05:00] all temporary modules stopped                 mode=docker openedge=master
failed to create master: listen unix var/run/openedge.sock: bind: address already in use

DEL var/run/openedge.sock file and can SKIP this error.

**Comment by xwdreamer** [comment]
follow this 4 steps:

1. sudo service docker stop
2. rm -r var/run/openedge.sock
3. sudo service docker start
4. bin/openedge -w .

**Comment by xwdreamer** [comment]
suggestion:

1. add openedge restart commond

**Comment by ludanfeng** [comment]
mac上执行：
kill -SIGTERM $(ps aux | grep openedge$ | awk '{print $2}')
