### ISSUE TITLE
按官方部署过程中mqttremote模块没有启动

### ISSUE THREAD

**Issue by leeruibin** [baidu/openedge#85]
**Describe the bug**
我按照官方的教程在本地部署其他模块都能正常启动，但mqttremote模块没有启动，使用的是docker模式部署的，请问这是什么原因?
系统是Ubuntu18.04，
![screenshot from 2019-01-18 15-13-15](https://user-images.githubusercontent.com/26408630/51371058-fa695580-1b33-11e9-9e9f-c6bc093a11b7.png)
docker版本
![screenshot from 2019-01-18 15-17-37](https://user-images.githubusercontent.com/26408630/51371132-3997a680-1b34-11e9-8a5a-293f8e8b89fa.png)

**Comment by ludanfeng** [comment]
看看var/db/openedge/module/modules.yml里面配了remote模块了吗？

**Comment by leeruibin** [comment]
没有，我之前也看到这个里边使没有配置remote的模块的，好像官方发布的OpenEdge程序包中的这个配置文件中都没有remote配置项，我在官方网站里也没有看到对应的remote模块的entry镜像的像，Darwin系统中的也是，请问能否告知一下这个的配置项。
不知道这算不算是官方文档的一个问题，这样跑起来的都和官网快速部署中启动结果不太一样，没有remote模块。
谢谢您的回复！

**Comment by ludanfeng** [comment]
@leeruibin 实例里默认是没有remote模块的，参考下面的文档通过云管理来配置试试，有问题再反馈。

- [创建远程MQTT模块配置](https://cloud.baidu.com/doc/BIE/CloudGettingStarted/36.5C.E5.BB.BA.E7.AB.8B.E5.BA.94.E7.94.A8.E9.85.8D.E7.BD.AE.html#.58.1F.79.1A.B6.BC.A7.D9.AF.18.46.18.B1.4E.4B.AE)

欢迎您加入[OpenEdge开发交流群](https://openedge.bj.bcebos.com/Wechat/Wechat-OpenEdge.png)

**Comment by leeruibin** [comment]
好的，谢谢您，已经加入群聊了，希望有后续问题能继续向您咨询！
