### ISSUE TITLE
why secret based authentication in baidu iothub mqtt connection need username?

### ISSUE THREAD

**Issue by xwdreamer** [baidu/openedge#88]
When i config remotehub module in openedge.
I found if i want to remote connec to baiddu iothub base on cetificate, I not only need to config cert path, but also need to config username.
**It is different from aws iot or azuer iot.**

==module.yml========================
name: remotehub
hub:
  address: tcp://localhub:1883
  username: test
  password: hahaha
remotes:
  - name: remote2
    address: ssl://xxxxx.mqtt.iot.gz.baidubce.com:1884
    clientid: 31231231231sdfasdfasdf
    **username: xxxxx/remotehub**
    ca: var/db/openedge/module/remotehub/cert-1111/ca.pem
    cert: var/db/openedge/module/remotehub/cert-1111/client.pem
    key: var/db/openedge/module/remotehub/cert-1111/client.key
    timeout: 30s
    interval: 1m
    keepalive: 30s
    meta:
      name: remote2
      resourceId: cert-uag3c6udo
rules:
  - id: rule-rcg3k6ytq
    hub:
      subscriptions:
        - topic: t1
          qos: 1
    remote:
      name: remote2
      subscriptions:
        - topic: t2
          qos: 1
===================

**Comment by ludanfeng** [comment]
because we use username to authenticate topics, and now we only support acl on username
