### ISSUE TITLE
在云端进行本地函数计算模块的配置时的问题

### ISSUE THREAD

**Issue by leeruibin** [baidu/openedge#89]
**Describe the bug**
在进行云端操作创建本地函数计算模块配置一项是不是不能在云端进行函数路由的配置，我已经在CFC页面创建了函数
![screenshot from 2019-01-21 15-57-41](https://user-images.githubusercontent.com/26408630/51460231-d6a54a00-1d95-11e9-8436-7484b850f2e5.png)

但是在创建函数路由的时候还是无法识别到我创建的函数
![screenshot from 2019-01-21 16-02-09](https://user-images.githubusercontent.com/26408630/51460312-07857f00-1d96-11e9-99bd-e3a21baf0467.png)

请问这个什么问题，是否能有更详细的说明，这中间该怎么操作，因为关于这一部分的操作描述都很省略
![screenshot from 2019-01-21 16-04-25](https://user-images.githubusercontent.com/26408630/51460419-559a8280-1d96-11e9-86fc-be4219bb9e21.png)
![screenshot from 2019-01-21 16-04-42](https://user-images.githubusercontent.com/26408630/51460420-56331900-1d96-11e9-9cd1-7722fe55f988.png)

**Comment by ludanfeng** [comment]
请先确认，BIE和CFC在不在一个region，都在北京还是都在广州。BIE目前不支持跨区选CFC的函数。

**Comment by leeruibin** [comment]
确实不在一个region，没注意这一点，谢谢
