### ISSUE TITLE
在教程中针对python运行时编写python脚本中加入第三方包引入说明

### ISSUE THREAD

**Issue by leeruibin** [baidu/openedge#95]
在官方教程中的如何针对python运行时编写脚本的一节中，如何引用第三方包这一小节，按照教程中的目录结构和示例代码配置之后无法成功运行，运行结果如下图所示，函数执行报错，希望能加入关于设置加载检索路径的详细说明
![screenshot from 2019-01-25 10-37-37](https://user-images.githubusercontent.com/26408630/51726349-deb8fe80-20a1-11e9-9061-ab7d0ab69740.png)

**Comment by kuailehaibin** [comment]
@leeruibin 
Python 中解决引入本地 package 的参考步骤为：

> + pip download `package_you_want_to_import` // 确定需要引入的 package 及其依赖
> + 在代码脚本执行路径放置上述需要引入 package 及其依赖 package 的源码
> + `touch __init__.py` // 使执行脚本所在目录成为一个 package
> + python `you_script.py` // 执行

对于文档中的case，需要引入的package为 requests，而通过 `pip download requests` 获知 requests 还会依赖 package idna、urllib3、chardet、certifi，把 requests package 的源码连同其依赖的 package 源码一同放入执行脚本目录，形成的目录结构及内容为：

<img width="1280" alt="requests-dir" src="https://user-images.githubusercontent.com/8502587/51786280-d7c2e680-219c-11e9-9f48-67079ad7b001.png">

其中，`get.py` 为具体执行脚本。
