### ISSUE TITLE
Nice to have a customer module example in cpp 

### ISSUE THREAD

**Issue by susu3621** [baidu/openedge#99]
**Is your feature request related to a problem? Please describe.**
Openedge framework is really nice, and easy to be ported to embedded system.
I really like the architecture in stead of kubernetes. And this is what I'm look for.
In most of the edge device, computing resources are limited.
Some heavy task, like video analysis, even the rtmp module is less efficiency.
In most of these case, people will use hardware accelerator to create their module on different platform, still c++ is the dominate language. 

**Describe the solution you'd like**
An opensource project probably be hard to cover all these hardware platform, but a c++ example will be good enough to guide user to create their own customize module.

But anyway, openedge team is doing pretty good job. Congratulations!

**Comment by ludanfeng** [comment]
@susu3621 

Thank you for your attention.
Considering the resource limitations of edge devices, CPP and Rust will be the first choice for our subsequent module development.
We will continue to embrace open thinking, abstract infrastructure, and provide development tools to help developers more easily develop modules and contribute to the community through OpenEdge to maximize value.

感谢您的关注。
考虑到边缘设备的资源限制，CPP和Rust将成为我们后续模块开发的首选。
我们将继续秉承开放的思想，抽象基础设施，并提供开发工具，帮助开发人员更容易地开发模块，并通过OpenEdge贡献给社区，以实现价值最大化。

**Comment by susu3621** [comment]
Thanks Danfeng, glad to hear it's on your roadmap.
I close this requirement.
